/**
 *     This file is part of GenCom.
 *
 *     GenCom is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     GenCom is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with GenCom.  If not, see <http://www.gnu.org/licenses/>.
 */
package main.java.edu.isistan.genCom.redSocial;

// Generated 06-mar-2014 11:43:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * LugaresDeTrabajo generated by hbm2java
 */
public class LugarDeTrabajo implements java.io.Serializable {

	private long id;
	private String direccion;
	private String nombre;
	private Set investigadoreses = new HashSet(0);
	private Set redeses = new HashSet(0);

	public LugarDeTrabajo() {
	}

	public LugarDeTrabajo(long id) {
		this.id = id;
	}

	public LugarDeTrabajo(long id, String direccion, String nombre,
			Set investigadoreses, Set redeses) {
		this.id = id;
		this.direccion = direccion;
		this.nombre = nombre;
		this.investigadoreses = investigadoreses;
		this.redeses = redeses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInvestigadoreses() {
		return this.investigadoreses;
	}

	public void setInvestigadoreses(Set investigadoreses) {
		this.investigadoreses = investigadoreses;
	}

	public Set getRedeses() {
		return this.redeses;
	}

	public void setRedeses(Set redeses) {
		this.redeses = redeses;
	}

}
