/**
 *     This file is part of GenCom.
 *
 *     GenCom is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     GenCom is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with GenCom.  If not, see <http://www.gnu.org/licenses/>.
 */
package main.java.edu.isistan.genCom.redSocial;

// Generated 06-mar-2014 11:43:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	private long publicacionId;
	private String titulo;
	private Set redeses = new HashSet(0);
	private Set investigadoreses = new HashSet(0);

	public Publicacion() {
	}

	public Publicacion(long publicacionId) {
		this.publicacionId = publicacionId;
	}

	public Publicacion(long publicacionId, String titulo, Set redeses,
			Set investigadoreses) {
		this.publicacionId = publicacionId;
		this.titulo = titulo;
		this.redeses = redeses;
		this.investigadoreses = investigadoreses;
	}

	public long getPublicacionId() {
		return this.publicacionId;
	}

	public void setPublicacionId(long publicacionId) {
		this.publicacionId = publicacionId;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Set getRedeses() {
		return this.redeses;
	}

	public void setRedeses(Set redeses) {
		this.redeses = redeses;
	}

	public Set getInvestigadoreses() {
		return this.investigadoreses;
	}

	public void setInvestigadoreses(Set investigadoreses) {
		this.investigadoreses = investigadoreses;
	}

}
